# Generated by Django 5.2.5 on 2025-09-02 10:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_rename_projects_or_slug_2cd6f6_idx_projects_or_slug_f7b32f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=32)),
                ('template', models.CharField(blank=True, max_length=128)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('md', 'Markdown'), ('csv', 'CSV')], default='pdf', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('storage_url', models.CharField(blank=True, max_length=1000)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project')),
            ],
            options={
                'ordering': ['-generated_at', '-created_at'],
                'indexes': [models.Index(fields=['project', 'created_at'], name='reports_rep_project_f356db_idx'), models.Index(fields=['status'], name='reports_rep_status_c732ef_idx'), models.Index(fields=['format'], name='reports_rep_format_b107b4_idx')],
            },
        ),
    ]
