# Generated by Django 5.2.5 on 2025-09-08 15:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_rename_projects_or_slug_2cd6f6_idx_projects_or_slug_f7b32f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('webhook', 'Webhook'), ('ms_teams', 'Microsoft Teams')], max_length=16)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to='projects.project')),
            ],
            options={
                'ordering': ['project__organization__name', 'project__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('event', models.CharField(choices=[('scan_completed', 'Scan Completed'), ('finding_created', 'Finding Created'), ('finding_updated', 'Finding Updated'), ('compliance_violation', 'Compliance Violation'), ('compliance_assessment_completed', 'Compliance Assessment Completed')], max_length=32)),
                ('severity_min', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='notifications.notificationchannel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='projects.project')),
            ],
            options={
                'ordering': ['project__organization__name', 'project__name', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='notificationchannel',
            index=models.Index(fields=['project', 'type'], name='notificatio_project_003229_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationchannel',
            index=models.Index(fields=['enabled'], name='notificatio_enabled_0b7997_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationchannel',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_notify_channel_project_name'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['project', 'event'], name='notificatio_project_5d60f9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['enabled'], name='notificatio_enabled_9fd611_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['severity_min'], name='notificatio_severit_5eeb37_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationrule',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_notify_rule_project_name'),
        ),
    ]
