# Generated by Django 5.2.5 on 2025-09-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organization',
            new_name='projects_or_slug_f7b32f_idx',
            old_name='projects_or_slug_2cd6f6_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_organiz_b32ce9_idx',
            old_name='projects_pr_organ_0a35b8_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_organiz_3cab48_idx',
            old_name='projects_pr_organ_08a505_idx',
        ),
    ]
