# Generated by Django 5.2.5 on 2025-09-02 09:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('targets', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minute', models.CharField(default='*', max_length=64)),
                ('hour', models.CharField(default='*', max_length=64)),
                ('day_of_week', models.CharField(default='*', max_length=64)),
                ('day_of_month', models.CharField(default='*', max_length=64)),
                ('month_of_year', models.CharField(default='*', max_length=64)),
                ('scanner', models.CharField(max_length=64)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('timezone_name', models.CharField(default='UTC', help_text='IANA timezone name', max_length=64)),
                ('window_start', models.CharField(blank=True, help_text='HH:MM format', max_length=5, null=True)),
                ('window_end', models.CharField(blank=True, help_text='HH:MM format', max_length=5, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='targets.target')),
            ],
            options={
                'ordering': ['-next_run_at', '-created_at'],
                'indexes': [models.Index(fields=['next_run_at', 'enabled'], name='schedules_s_next_ru_082542_idx'), models.Index(fields=['target'], name='schedules_s_target__b7a207_idx'), models.Index(fields=['scanner'], name='schedules_s_scanner_7571da_idx')],
            },
        ),
    ]
