# Generated by Django 5.2.5 on 2025-09-02 08:50

import django.db.models.deletion
import django.utils.timezone
import evidence.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('findings', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('screenshot', 'Screenshot'), ('log', 'Log'), ('request', 'Request'), ('response', 'Response'), ('artifact', 'Artifact'), ('other', 'Other')], default='other', max_length=16)),
                ('file', models.FileField(blank=True, help_text='Uploaded evidence file', null=True, upload_to=evidence.models.evidence_upload_path)),
                ('storage_url', models.CharField(blank=True, help_text='External storage URL or path to the evidence blob', max_length=1000)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, help_text='Hash of content if available', max_length=64)),
                ('request_id', models.CharField(blank=True, max_length=128)),
                ('response_id', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='findings.finding')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind'], name='evidence_ev_kind_70a4cc_idx'), models.Index(fields=['created_at'], name='evidence_ev_created_6c2b4d_idx')],
            },
        ),
    ]
