# Generated by Django 5.2.5 on 2025-09-08 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
        ('findings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='correlation_id',
            field=models.CharField(blank=True, help_text='ID for correlating related evidence', max_length=128),
        ),
        migrations.AddField(
            model_name='evidence',
            name='correlation_type',
            field=models.CharField(blank=True, help_text="Type of correlation (e.g., 'request_response', 'vulnerability_chain')", max_length=64),
        ),
        migrations.AddField(
            model_name='evidence',
            name='parent_evidence',
            field=models.ForeignKey(blank=True, help_text='Parent evidence for hierarchical relationships', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_evidence', to='evidence.evidence'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags for evidence categorization and search'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='kind',
            field=models.CharField(choices=[('screenshot', 'Screenshot'), ('log', 'Log'), ('request', 'Request'), ('response', 'Response'), ('request_response', 'Request/Response'), ('artifact', 'Artifact'), ('other', 'Other')], default='other', max_length=16),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['correlation_id'], name='evidence_ev_correla_3a931b_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['correlation_type'], name='evidence_ev_correla_4ac049_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['parent_evidence'], name='evidence_ev_parent__3ef717_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['finding', 'kind'], name='evidence_ev_finding_77b2da_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['finding', 'correlation_id'], name='evidence_ev_finding_9da30d_idx'),
        ),
    ]
