# Generated by Django 5.2.5 on 2025-09-02 10:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_rename_projects_or_slug_2cd6f6_idx_projects_or_slug_f7b32f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('type', models.CharField(choices=[('web', 'Web'), ('api', 'API'), ('host', 'Host'), ('mobile', 'Mobile'), ('repo', 'Repository'), ('other', 'Other')], default='web', max_length=16)),
                ('address', models.CharField(help_text='Hostname, URL, IP/CIDR, package name, or identifier', max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='projects.project')),
            ],
            options={
                'ordering': ['project__organization__name', 'project__name', 'name'],
                'indexes': [models.Index(fields=['project', 'slug'], name='targets_tar_project_315778_idx'), models.Index(fields=['project', 'name'], name='targets_tar_project_6dd9f4_idx'), models.Index(fields=['type'], name='targets_tar_type_78e889_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'slug'), name='uniq_target_project_slug')],
            },
        ),
    ]
