# Generated by Django 5.2.5 on 2025-09-02 09:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('scans', '__first__'),
        ('targets', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('fixed', 'Fixed'), ('false_positive', 'False Positive'), ('risk_accepted', 'Risk Accepted'), ('suppressed', 'Suppressed')], db_index=True, default='open', max_length=16)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('dedupe_hash', models.CharField(help_text='Deterministic hash for deduplication within a target', max_length=64)),
                ('locations', models.JSONField(blank=True, default=list, help_text='List of affected locations/paths/URLs')),
                ('evidence_refs', models.JSONField(blank=True, default=list, help_text='IDs/refs of linked evidence (populated later)')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compliance_controls', models.ManyToManyField(blank=True, help_text='Compliance controls this finding violates', related_name='findings', to='compliance.compliancecontrol')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='scans.scan')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='targets.target')),
            ],
            options={
                'ordering': ['-severity', '-last_seen_at'],
                'indexes': [models.Index(fields=['severity'], name='findings_fi_severit_95e77d_idx'), models.Index(fields=['status'], name='findings_fi_status_8e463e_idx'), models.Index(fields=['last_seen_at'], name='findings_fi_last_se_0e7413_idx')],
                'constraints': [models.UniqueConstraint(fields=('target', 'dedupe_hash'), name='uniq_finding_target_dedupe')],
            },
        ),
    ]
