# Generated by Django 5.2.5 on 2025-09-02 09:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_rename_projects_or_slug_2cd6f6_idx_projects_or_slug_f7b32f_idx_and_more'),
        ('targets', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceFramework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(choices=[('owasp_top_ten', 'OWASP Top Ten'), ('pci_dss', 'PCI DSS'), ('hipaa', 'HIPAA'), ('gdpr', 'GDPR'), ('iso_27001', 'ISO 27001'), ('nist', 'NIST')], max_length=32)),
                ('version', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['type', 'name'],
                'indexes': [models.Index(fields=['type'], name='compliance__type_5d55a7_idx'), models.Index(fields=['is_active'], name='compliance__is_acti_8b196c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('requirement', 'Requirement'), ('control', 'Control'), ('best_practice', 'Best Practice')], default='requirement', max_length=16)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='compliance.complianceframework')),
            ],
            options={
                'ordering': ['framework', 'control_id'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('partially_compliant', 'Partially Compliant'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('overall_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('control_scores', models.JSONField(blank=True, default=dict)),
                ('findings_count', models.JSONField(blank=True, default=dict)),
                ('last_assessed_at', models.DateTimeField(blank=True, null=True)),
                ('next_assessment_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_assessments', to='projects.project')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_assessments', to='targets.target')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='compliance.complianceframework')),
            ],
            options={
                'ordering': ['-last_assessed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finding_type', models.CharField(max_length=128)),
                ('finding_pattern', models.CharField(blank=True, max_length=255)),
                ('mapping_type', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=16)),
                ('confidence', models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='compliance.compliancecontrol')),
            ],
            options={
                'ordering': ['control', 'finding_type'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceTag',
            fields=[
                ('slug', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='OWASP', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'slug'],
                'indexes': [models.Index(fields=['category'], name='compliance__categor_af1b9a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='compliancecontrol',
            index=models.Index(fields=['framework', 'control_id'], name='compliance__framewo_093213_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecontrol',
            index=models.Index(fields=['type'], name='compliance__type_918ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecontrol',
            index=models.Index(fields=['severity'], name='compliance__severit_6d04e3_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecontrol',
            index=models.Index(fields=['is_active'], name='compliance__is_acti_1d0b3d_idx'),
        ),
        migrations.AddConstraint(
            model_name='compliancecontrol',
            constraint=models.UniqueConstraint(fields=('framework', 'control_id'), name='uniq_control_framework_id'),
        ),
        migrations.AddIndex(
            model_name='complianceassessment',
            index=models.Index(fields=['framework', 'assessment_status'], name='compliance__framewo_6ec80f_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceassessment',
            index=models.Index(fields=['target', 'compliance_status'], name='compliance__target__fb5a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceassessment',
            index=models.Index(fields=['project', 'assessment_status'], name='compliance__project_e08d92_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceassessment',
            index=models.Index(fields=['last_assessed_at'], name='compliance__last_as_92cda9_idx'),
        ),
        migrations.AddConstraint(
            model_name='complianceassessment',
            constraint=models.UniqueConstraint(fields=('framework', 'target'), name='uniq_assessment_framework_target'),
        ),
        migrations.AddIndex(
            model_name='compliancemapping',
            index=models.Index(fields=['finding_type'], name='compliance__finding_7a3d1f_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancemapping',
            index=models.Index(fields=['mapping_type'], name='compliance__mapping_326cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancemapping',
            index=models.Index(fields=['is_active'], name='compliance__is_acti_c2126b_idx'),
        ),
        migrations.AddConstraint(
            model_name='compliancemapping',
            constraint=models.UniqueConstraint(fields=('control', 'finding_type'), name='uniq_mapping_control_finding'),
        ),
    ]
