# Generated by Django 5.2.5 on 2025-09-02 10:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scanner', models.CharField(help_text='Scanner backend identifier, e.g., zap, nuclei', max_length=64)),
                ('type', models.CharField(choices=[('active', 'Active'), ('passive', 'Passive'), ('scheduled', 'Scheduled'), ('manual', 'Manual')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=16)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='targets.target')),
            ],
            options={
                'ordering': ['-started_at', '-created_at'],
                'indexes': [models.Index(fields=['target', 'started_at'], name='scans_scan_target__a679f7_idx'), models.Index(fields=['status'], name='scans_scan_status_fe0149_idx')],
            },
        ),
    ]
